### ISSUE TITLE
assemble engine

### ISSUE THREAD

**Issue by jonschlinkert** [oncletom/emunova.net#18]
@oncletom I noticed that you explicitly defined the engine in the assemble task options, here: https://github.com/oncletom/emunova.net/blob/master/Gruntfile.js#L105

Since Handlebars is already the default engine, you can remove that. which should allow you to use partials without `.hbs`, e.g. `{{> footer }}` instead of `{{> footer.hbs}}`

**Comment by oncletom** [comment]
Not relevant anymore as the website is built with [Hugo](https://gohugo.io/) — #52
